### ISSUE TITLE
SQLite not installed in Python3

### ISSUE THREAD

**Issue by JamesHaskell** [disarticulate/docker-python-sqlite#1]
SQLite seems to be missing from Python3. 
1. Run the container.
2. Enter: "import SQLite3" at the Python prompt- gives an error.

```
>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.5/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named '_sqlite3'
>>> import sqlite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'sqlite'
```

**Comment by disarticulate** [comment]
went a little to far cleaning upl

Sqlite3-dev needs to be installed prior to installing/upgrading sqlite3.

Fixed.

https://github.com/disarticulate/docker-python-sqlite/commit/2e7d58a41714b1c4bae4bc18a9e025e073de5cfe

**Comment by JamesHaskell** [comment]
Thanks Eric!!

**Comment by JamesHaskell** [comment]
I'm still having trouble with this... still receiving the error I first submitted when running 3.12:

docker run -it --rm prolocutor/docker-python-sqlite:3.12 /bin/sh
/ # python
Python 3.5.1 (default, May 25 2016, 02:01:28)
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

> > > import sqlite3
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python3.5/sqlite3/**init**.py", line 23, in <module>
> > >     from sqlite3.dbapi2 import *
> > >   File "/usr/local/lib/python3.5/sqlite3/dbapi2.py", line 27, in <module>
> > >     from _sqlite3 import *
> > > ImportError: No module named '_sqlite3'
